---
openapi: 3.0.2
info:
  title: PosWS
  version: 1.0.0
  description: API to receive transaction data from POS
paths:
  /transactions:
    summary: Path used to receive transaction data
    description: The REST endpoint/path used to create transaction. This path contains
      a `POST` operation
    post:
      requestBody:
        description: Transaction data from H&LPOS must be a valid JSON
        content:
          application/json: {}
        required: true
      responses:
        "201":
          description: Successful response. When transaction data is successfully
            stored using `POST` request.
        "400":
          description: Response when data can't be stored successfully
        "500":
          description: When unexpected error occurs processing the request
      security:
      - HTTP-Basic: []
      summary: Receive transaction data from POS and persist it in DB
components:
  securitySchemes:
    HTTP-Basic:
      scheme: basic
      type: http
security:
- HTTP-Basic: []
